version: "2.1"

volumes:
  adguardhome_work: {}
  adguardhome_conf: {}

services:
    # https://hub.docker.com/r/adguard/adguardhome
  adguard:
    build: adguard
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - "adguardhome_work:/opt/adguardhome/work:rw"
      - "adguardhome_conf:/opt/adguardhome/conf:rw"

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname:latest@sha256:b923d6ea886ec48125d2c49e431638d2ef6f4adac574b729b4135cfade3ffdce
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: adguard
