name: balena

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [gh_otkd/dark-sea]

    steps:
      - uses: actions/checkout@main
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          versionbot: false
          create_tag: true
      - name: Build ID Logger
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
